### ISSUE TITLE
getblocktemplate returns OOM error

### ISSUE THREAD

**Issue by azilber** [LIMXTEC/Bitcloud#10]
"version" : 2000007

Running ./bitcloud-cli getblocktemplate returns:

`error: {"code":-7,"message":"Out of memory"}`

Expecting to see a block template.  Tested on system with 8gb of ram.   This is not an actual system error.  Something is not allocating properly...

**Comment by quasarbeast** [comment]
I confirm this error still present.

what do we expect getblocktemplate to do?

**Comment by limxdev** [comment]
This command is still not supported. You can him only use in the POW Phase. (Already done)

**Comment by luk6173** [comment]
Ok, please close this issue @limxdev
