### ISSUE TITLE
Bitcloud BTDX 2.0.2.0 High Sierra release 

### ISSUE THREAD

**Issue by tofra** [LIMXTEC/Bitcloud#11]
When can we expect that?

Regards,
Tom

**Comment by tofra** [comment]
@limxdev ?

**Comment by dArkjON** [comment]
Hey Tom,
a update will be availible asap.

Greetings
Jon

**Comment by limxdev** [comment]
Please check the newest build!

**Comment by tofra** [comment]
Worked fine!
