### ISSUE TITLE
High Sierra Bitcloud BTDX 2.1.x

### ISSUE THREAD

**Issue by 2ge** [LIMXTEC/Bitcloud#15]
Hi,

any ETA on this ? We have to use really old release of Bitcloud now.

**Comment by azilber** [comment]
What release are you using on HS?

**Comment by azilber** [comment]
Try my Mojave build, in theory, it should work for you:
https://github.com/ConsulTent/Bitcloud/releases/tag/2.1.0.1.2

**Comment by 2ge** [comment]
Hi, 

yes this helps, it is not normally possible to run it, but using Show Contents in Finder and navigating to MacOS dir is possible to execute binary. Thanks for help

**Comment by azilber** [comment]
Could you please post a screenshot of the error/issue with the binary?

If you could open an issue here: https://github.com/ConsulTent/Bitcloud/issues

**Comment by 2ge** [comment]
done https://github.com/ConsulTent/Bitcloud/issues/2

**Comment by azilber** [comment]
@limxdev you can close this issue, it's resolved. 👍
