### ISSUE TITLE
binding to 51473 port

### ISSUE THREAD

**Issue by 2ge** [LIMXTEC/Bitcloud#4]
Hi,

I am trying to run PIVX MN and BitCloud MN on same server. It seems both projects are using same ports, when I run pivxd and then I start bitcloudd:

```
$ bitcloudd
BTDX server starting
Error: An error occurred while setting up the RPC address 0.0.0.0 port 51473 for listening: bind: Address already in use

$ lsof -i :51473
COMMAND   PID  USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
pivxd   22281 an    8u  IPv6 216422632      0t0  TCP *:51473 (LISTEN)
```

how to fix this ?

**Comment by 2ge** [comment]
rpcport=51474 for example in config. upnp=1 is also helping.

**Comment by limxdev** [comment]
We change it in the next version.
