### ISSUE TITLE
Building v2.0.0.6 on Linux missing libtool

### ISSUE THREAD

**Issue by azilber** [LIMXTEC/Bitcloud#8]
After running configure:

./configure: line 31411: libtool: No such file or directory
mv: cannot stat 'libtool-2': No such file or directory
chmod: cannot access 'libtool': No such file or directory

**Comment by limxdev** [comment]
Please install all libraries.

https://github.com/LIMXTEC/Bitcloud/blob/master/doc/build-unix.md
